apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: c-tessera-job
  namespace: c-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: c-tessera-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-tessera-key-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-skk
      namespace: flux-skk
  values:
    metadata:
      name: c-tessera-job
      namespace: c-bes
    peer:
      name: c
    image:
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
      pullPolicy: IfNotPresent
      alpineutils: ghcr.io/hyperledger/bevel-alpine-ext:latest
    vault:
      address: http://demo.sau99.dev.aws.blockchaincloudpoc-develop.com
      secretengine: secretsv2
      authpath: besuc
      role: vault-role
      keyprefix: c-bes/crypto
      serviceaccountname: vault-auth
      tmprefix: data/c-bes/crypto
      type: hashicorp

