apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: v1-ambassador-job
  namespace: sc-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: v1-ambassador-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/besu-tlscert-cert-gen
    sourceRef:
      kind: GitRepository
      name: flux-skk
      namespace: flux-skk
  values:
    metadata:
      name: v1-ambassador-job
      namespace: sc-bes
    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: regcred
      pullPolicy: IfNotPresent
    network:
      tmtls: True
    node:
      name: v1
      clientport: 8888
    vault:
      address: http://demo.sau99.dev.aws.blockchaincloudpoc-develop.com
      secretengine: secretsv2
      authpath: besusc
      rootcasecret: data/sc-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: data/sc-bes/crypto/v1/tls
      role: vault-role
      serviceaccountname: vault-auth
      type: hashicorp
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: v1.sau99.dev.aws.blockchaincloudpoc-develop.com
      domain_name_priv: v1.sc-bes
      domain_name_tessera: v1-tessera.sc-bes
    healthcheck:
      retries: 10
      sleepTimeAfterError: 2

