name: Deploy to AWS Cluster

on:
  push:
    branches:
      - ent-flow
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: ${{ secrets.VAULT_URL }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      VAULT_SERVER: ${{ secrets.VAULT_SERVER }}
      VAULT_PORT: ${{ secrets.VAULT_PORT }}
      VAULT_BASTION: ${{ secrets.VAULT_BASTION }}
      VAULT_USER: ${{ vars.VAULT_USER }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Set KUBECONFIG
        run: |
          mkdir -p .kube/config
          echo "${{ secrets.ENCODED_KUBECONFIG }}" | base64 --decode > .kube/config/decoded-kubeconfig
          export KUBECONFIG="$(pwd)/.kube/config/decoded-kubeconfig"

      - name: Install HashiCorp Vault CLI
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: Local DNS Mapping
        run: |
          sudo bash -c 'echo "127.0.0.1 vault.internal.dev.aws.blockchaincloudpoc-develop.com" >> /etc/hosts'

      - name: Add SSH Rule to Security Group
        run: |
          curl https://ipv4.icanhazip.com/ > localip
          aws ec2 authorize-security-group-ingress \
            --group-id "sg-03bd095e7b92149f8" \
            --protocol "tcp" \
            --port "22" \
            --cidr "$(cat localip)/32" \
            --region "eu-west-1"

      - name: Create Tunnel
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ENCODED_DEVENV_BASTION_PEM }}" | base64 --decode > ~/.ssh/vault.pem
          chmod 600 ~/.ssh/vault.pem
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan ${VAULT_BASTION} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/vault.pem -f -q -N -L "${{ env.VAULT_PORT }}:${{ env.VAULT_SERVER }}:${{ env.VAULT_PORT }}" "${{ env.VAULT_USER }}@${{ env.VAULT_BASTION }}" -v

      - name: Remove SSH Rule from Security Group
        run: |
          curl https://ipv4.icanhazip.com/ > localip
          aws ec2 revoke-security-group-ingress \
            --group-id "sg-03bd095e7b92149f8" \
            --protocol "tcp" \
            --port "22" \
            --cidr "$(cat localip)/32" \
            --region "eu-west-1"
