name: Deploy to AWS Cluster

on:
  push:
    branches:
      - ent-flow
  workflow_dispatch:

jobs:
  # deployment:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   env:
  #     AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  #     AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  #     AWS_REGION_NAME: "${{ secrets.AWS_REGION_NAME }}"
  #     AWS_SECURITY_GROUP_ID: "${{ secrets.AWS_SECURITY_GROUP_ID }}"
  #     ENCODED_KUBECONFIG: "${{ secrets.ENCODED_KUBECONFIG }}"
  #     ENCODED_DEVENV_BASTION_PEM: "${{ secrets.ENCODED_DEVENV_BASTION_PEM }}"
  #     VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"
  #     VAULT_SERVER: "${{ secrets.VAULT_SERVER }}"
  #     VAULT_PORT: "${{ secrets.VAULT_PORT }}"
  #     VAULT_TOKEN: "${{ secrets.VAULT_TOKEN }}"
  #     VAULT_BASTION: "${{ secrets.VAULT_BASTION }}"
  #     VAULT_USER: "${{ vars.VAULT_USER }}"
  #     GITHUB_USER_NAME: "${{ secrets.GH_USER_NAME }}"
  #     GITHUB_EMAIL_ADDR: "${{ secrets.GH_EMAIL_ADDR }}"
    aws-setup:
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        AWS_REGION_NAME: "${{ secrets.AWS_REGION_NAME }}"
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: "${{ env.AWS_ACCESS_KEY_ID }}"
            aws-secret-access-key: "${{ env.AWS_SECRET_ACCESS_KEY }}"
            aws-region: "${{ env.AWS_REGION_NAME }}"

        - name: AWS Commands
          run: |
            echo "aws --version" && aws --version
            echo "aws configure list" && aws configure list  
            echo "sts get-caller-identity" && aws sts get-caller-identity

    git-and-github-setup:
      runs-on: ubuntu-latest
      needs: aws-setup
      permissions:
        contents: write
      env:
        GITHUB_USER_NAME: "${{ secrets.GH_USER_NAME }}"
        GITHUB_EMAIL_ADDR: "${{ secrets.GH_EMAIL_ADDR }}"
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2.4.0

        - name: AWS Commands
          run: |
            echo "aws --version" && aws --version
            echo "aws configure list" && aws configure list  
            echo "sts get-caller-identity" && aws sts get-caller-identity

        - name: Display Git Information
          run: |
            env
            git --version
            git branch
            git log -1

        - name: Configure Git
          run: |
            git config --global user.email "${{ env.GITHUB_EMAIL_ADDR }}"
            git config --global user.name "${{ env.GITHUB_USER_NAME }}"

            echo "Create file"
            touch SAURABH.txt
            echo "Hello" >> SAURABH.txt

            echo "List all files at $(pwd)"
            ls

            echo "Push changes"
            git add .
            git commit -m "Your commit message"
            git push origin ent-flow
            git pull origin ent-flow

            echo "#################################5"
            echo "Delete the same file"
            rm -rf SAURABH.txt

            echo "Push changes again"
            git add .
            git commit -m "Your commit message"
            git push origin ent-flow

            echo "Git Push and Pull"
            git pull origin ent-flow
            git push origin ent-flow
